package yfquery

import "testing"

func TestLeaguesQuery(t *testing.T) {
	testQueries(t,
		[]testQueryPair{
			{
				Leagues(),
				"/leagues",
			},
			{
				Leagues().Keys([]string{"nba.l.12345", "nba.l.67890"}),
				"/leagues;league_keys=nba.l.12345,nba.l.67890",
			},
			{
				Leagues().Key("nba.l.12345"),
				"/leagues;league_keys=nba.l.12345",
			},
			{
				Leagues().Key("nba.l.12345").Key("nba.l.67890"),
				"/leagues;league_keys=nba.l.67890",
			},
			{
				Leagues().Key("nba.l.12345").Settings(),
				"/leagues;league_keys=nba.l.12345/settings",
			},
			{
				Leagues().Key("nba.l.12345").CurrentScoreboard(),
				"/leagues;league_keys=nba.l.12345/scoreboard",
			},
			{
				Leagues().Key("nba.l.12345").Scoreboard(1),
				"/leagues;league_keys=nba.l.12345/scoreboard;week=1",
			},
			{
				Leagues().Key("nba.l.12345").Standings(),
				"/leagues;league_keys=nba.l.12345/standings",
			},
			{
				Leagues().Key("nba.l.12345").Standings().CurrentScoreboard(),
				"/leagues;league_keys=nba.l.12345;out=standings,scoreboard",
			},
			{
				Leagues().Key("nba.l.12345").DraftResults(),
				"/leagues;league_keys=nba.l.12345/draftresults",
			},
			{
				Leagues().Key("nba.l.12345").TeamsWithDefaults(),
				"/leagues;league_keys=nba.l.12345/teams",
			},
			{
				Leagues().Key("nba.l.12345").PlayersWithDefaults(),
				"/leagues;league_keys=nba.l.12345/players",
			},
			{
				Leagues().Key("nba.l.12345").TransactionsWithDefaults(),
				"/leagues;league_keys=nba.l.12345/transactions",
			},
			{
				Leagues().Key("nba.l.12345").Teams().Key("nba.l.12345.t.1"),
				"/leagues;league_keys=nba.l.12345/teams;team_keys=nba.l.12345.t.1",
			},
			{
				Leagues().Key("nba.l.12345").Players().Search("Kevin Durant"),
				"/leagues;league_keys=nba.l.12345/players;search=Kevin+Durant",
			},
			{
				Leagues().Key("nba.l.12345").Transactions().Types([]string{"add", "drop"}),
				"/leagues;league_keys=nba.l.12345/transactions;types=add,drop",
			},
		})
}

func TestLeagueQuery(t *testing.T) {
	testQueries(t,
		[]testQueryPair{
			{
				League(),
				"/league",
			},
			{
				League().Key("nba.l.12345"),
				"/league/nba.l.12345",
			},
			{
				League().Key("nba.l.12345").Settings(),
				"/league/nba.l.12345/settings",
			},
			{
				League().Key("nba.l.12345").CurrentScoreboard(),
				"/league/nba.l.12345/scoreboard",
			},
			{
				League().Key("nba.l.12345").Scoreboard(1),
				"/league/nba.l.12345/scoreboard;week=1",
			},
			{
				League().Key("nba.l.12345").Standings(),
				"/league/nba.l.12345/standings",
			},
			{
				League().Key("nba.l.12345").Standings().CurrentScoreboard(),
				"/league/nba.l.12345;out=standings,scoreboard",
			},
			{
				League().Key("nba.l.12345").DraftResults(),
				"/league/nba.l.12345/draftresults",
			},
			{
				League().Key("nba.l.12345").TeamsWithDefaults(),
				"/league/nba.l.12345/teams",
			},
			{
				League().Key("nba.l.12345").PlayersWithDefaults(),
				"/league/nba.l.12345/players",
			},
			{
				League().Key("nba.l.12345").TransactionsWithDefaults(),
				"/league/nba.l.12345/transactions",
			},
			{
				League().Key("nba.l.12345").Teams().Key("nba.l.12345.t.1"),
				"/league/nba.l.12345/teams;team_keys=nba.l.12345.t.1",
			},
			{
				League().Key("nba.l.12345").Players().Search("Kevin Durant"),
				"/league/nba.l.12345/players;search=Kevin+Durant",
			},
			{
				League().Key("nba.l.12345").Transactions().Types([]string{"add", "drop"}),
				"/league/nba.l.12345/transactions;types=add,drop",
			},
		})
}
